url: 'https://github.com/sstroth/ghpages-test'
baseurl: '/ghpages-test'

# Site settings
title: PALAIMON
email: your-email@domain.com
description: "This is our company website. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Me Myself and I
        Quantitative Analyses
          Topics
          -- E-Commerce
          -- Retail
          -- Marketing
          --Social Media
          Applications
          -- Dashboarding
          -- Research Studies
          --Live-Monitoring

  pic: 1
  doing: wird nicht angezeigt
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: IB
  pic: 2
  doing: Data Stuff
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: tbd
  pic: 3
  doing: Data Engineering
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Berlin
  - line: Germany

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["README.md"]
